apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-cicd
  namespace: go-cicd
spec:
  selector:
    matchLabels:
      app: go-cicd
  template:
    metadata:
      labels:
        app: go-cicd
    spec:
      containers:
      - name: go-cicd
        image: 107995894928.dkr.ecr.us-west-2.amazonaws.com/go-cicd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

